set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

if(HPCC_TOOLCHAIN_DIR AND NOT PPLCV_TOOLCHAIN_DIR)
    message(FATAL_ERROR "`HPCC_TOOLCHAIN_DIR` is deprecated. use `PPLCV_TOOLCHAIN_DIR` instead.")
endif()

if(NOT PPLCV_TOOLCHAIN_DIR)
    set(PPLCV_TOOLCHAIN_DIR "/usr")
    if(NOT EXISTS ${PPLCV_TOOLCHAIN_DIR})
        message(FATAL_ERROR "`PPLCV_TOOLCHAIN_DIR` not set.")
    endif()
elseif(NOT EXISTS ${PPLCV_TOOLCHAIN_DIR})
    message(FATAL_ERROR "`PPLCV_TOOLCHAIN_DIR`(${PPLCV_TOOLCHAIN_DIR}) not found.")
endif()

set(CMAKE_C_COMPILER ${PPLCV_TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${PPLCV_TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
